sudo: false
cache:
  directories:
  - $HOME/buildout-cache
language: python
python:
  - 2.7
env:
  - PLONE=4.3
  - PLONE=5.0
  - PLONE=5.1
matrix:
  exclude:
    - python: 2.6
      env: PLONE=4.3
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - bootstrap.sh test-$PLONE.x.cfg
  - bin/buildout -c test-$PLONE.x.cfg -N
script: bin/code-analysis && bin/test
after_success:
# XXX: https://github.com/urllib3/urllib3/issues/1456
- pip install urllib3==1.23
- pip install coverage
- coverage run bin/test
- pip install coveralls
- coveralls
