sudo: false
cache:
  directories:
  - $HOME/buildout-cache
language: python
python:
  - 2.7
env:
  - PLONE=4.3
  - PLONE=5.0
  - PLONE=5.1
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.1
    - python: 2.6
      env: PLONE=4.2
    - python: 2.6
      env: PLONE=4.3
    - python: 2.6
      env: PLONE=5.0
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N
script: bin/code-analysis && bin/test
script: bin/test
after_success:
  - bin/coverage.sh 75 && pip install -q coveralls==0.5 && coveralls || true
